# Generated by Django 4.1.5 on 2023-02-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comentario_heladera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario_heladera',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentario_notebook',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentario_televisor',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='lavarropa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario_celular',
        ),
        migrations.DeleteModel(
            name='Comentario_heladera',
        ),
        migrations.DeleteModel(
            name='Comentario_notebook',
        ),
        migrations.DeleteModel(
            name='Comentario_televisor',
        ),
        migrations.DeleteModel(
            name='Lavarropa',
        ),
    ]
