# Generated by Django 4.1.5 on 2023-01-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_celular_heladera_lavarropa_notebook_televisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='imagenCelular',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='heladera',
            old_name='imagenHeladera',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='lavarropa',
            old_name='imagenLavarropa',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='imagenNotebook',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='televisor',
            old_name='imagenTv',
            new_name='imagen',
        ),
    ]
