# Generated by Django 4.1.5 on 2023-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_rename_imagencelular_celular_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes/'),
        ),
    ]
